  const success_msg = {
    otpSentToPhone: "OTP sent to your registered phone number.",
    otpResentToPhone: "OTP resent successfully.",
    otpSentToEmail: "OTP sent to your registered email address.",
    otpResentToEmail: "OTP resent successfully.",
    otpExpiredWarning: "Warning: Your OTP has expired. Please request a new OTP.",
    maxResendAttemptsReached: "Maximum OTP resend attempts reached. Please try again later.",
    exceededMaxResendAttempts: "Exceeded maximum OTP resend attempts. Please try again later.",
    otpVerificationSuccess: "OTP verification successful. You can now reset your password.",
    resendOtpAfter30s: "Resend OTP will be available after 30 seconds.",
    resendOtpAfter1Minute: "Resend OTP will be available after 1 minute.",
    signupSuccess: "Sign-up successful. Welcome to our platform!",
    signupVerificationSuccess: "Thank you for signing up. You can now log in.",
    loginSuccess: "Welcome back! You are now logged in.",
    loginSuccessWithGreeting: "Login successful. Welcome!",
    emailVerified: "Email verified successfully.",
    phoneNumberVerified: "Phone number verified successfully.",
    twoFactorAuthEnabled: "Two-factor authentication enabled.",
    twoFactorAuthSuccess: "Two-factor authentication successful.",
    passwordResetSuccess: "Password reset successful.",
    accountDeletionSuccess: "Account deletion successful.",
    passwordChangeSuccess: "Password changed successfully.",
    verificationEmailSent: "Verification email sent. Please check your inbox.",
    verificationPhoneSent: "Verification message sent. Please check your phone messages.",
    passwordResetLinkSent: "Password reset link sent. Check your email.",
    accountActivationSuccess: "Account activated successfully.",
    profileCompletionSuccess: "Profile completed successfully.",
    twoFactorAuthDisabled: "Two-factor authentication disabled.",
    emailConfirmed: "Email address confirmed successfully.",
    phoneNumberConfirmed: "Phone number confirmed successfully.",
    accountDeletionRequestReceived: "Account deletion request received.",
    accountRecoverySuccess: "Account recovery successful.",
    subscribedToEmailUpdates: "Successfully subscribed to email updates.",
    newsletterSubscriptionSuccess: "Newsletter subscription successful.",
    accountInfoUpdateSuccess: "Account information updated successfully.",
    unsubscribedFromEmailUpdates: "Successfully unsubscribed from email updates.",
    newsletterUnsubscribeSuccess: "Newsletter unsubscribed successfully.",
    accountPasswordResetSuccess: "Account password reset successful.",
    accountRecoveryOptionUpdateSuccess: "Account recovery option updated successfully.",
    accountSecuritySettingsUpdateSuccess: "Account security settings updated successfully.",
    twoFactorAuthReenabled: "Two-factor authentication enabled.",
    passwordChangedAfter2FA: "Password changed successfully.",
    profileUpdateSuccess:"Profile update successfully",
    logoutSuccess:"Logged out!",
    accountBlockedSuccess: "Account Blocked!",
    accountDeactiveSuccess: "Account De-activated.",
    ratingSuccess: "Thank you for taking the time to rate DreamsGrant! Your feedback is invaluable and helps us enhance your experience",
    ratingUpdateSuccess: "You have successfully edited the Rating",
    favouriteProductAdd: "Product added to your favourite list",
    favouriteProductRemove: "Product removed from your favouiret list",
    votesuccess: "Great choice! Your vote has been successfully submitted. Thanks for being an active participant!",
    productDeleted: "Product deleted successfully"
  };
  
  const register_msg = {
    enterFirstName: "Please enter your first name.",
    invalidCharsInFirstName: "First name contains invalid characters. Please use alphabets only.",
    firstNameTooLong: "The first name is too long. Please shorten it and try again.",
    enterLastName: "Please enter your last name.",
    invalidCharsInLastName: "Last name contains invalid characters. Please use alphabets only.",
    lastNameTooLong: "The last name is too long. Please shorten it and try again.",
    enterFullName: "Please enter your full name.",
    invalidCharsInFullName: "Full name contains invalid characters. Please use alphabets only.",
    fullNameTooLong: "The full name is too long. Please shorten it and try again.",
    enterDisplayName: "Please enter your display name.",
    invalidCharsInDisplayName: "Display name contains invalid characters. Please use alphabets, numbers, and underscores only.",
    displayNameTooLong: "The display name is too long. Please shorten it and try again.",
    enterFirstAndLastName: "Please enter both your first name and last name.",
    fullNameCannotContainDigits: "Full name cannot contain numeric digits. Please use alphabets only.",
    firstNameMinLength: "The first name must be at least 2 characters long.",
    firstNameCannotContainSpecialChars: "First name cannot contain numbers or special characters. Please use alphabets only.",
    lastNameCannotContainSpecialChars: "Last name cannot contain numbers or special characters. Please use alphabets only.",
    displayNameAlreadyInUse: "The display name you entered is already in use. Please choose another.",
    displayNameMinLength: "The display name must be at least 3 characters long.",
    fullNameInappropriateWords: "The full name contains inappropriate words. Please enter a valid full name.",
    lastNameMinLength: "The last name must be at least 2 characters long.",
    enterFirstNameToContinue: "Please enter your first name to continue.",
    enterLastNameToContinue: "Please enter your last name to continue.",
    enterFullNameToContinue: "Please enter your full name to continue.",
    displayNameTooLongShortenName: "The display name is too long. Please use a shorter name.",
    avoidExcessiveSpacesInName: "Please avoid using excessive spaces in your name.",
    fullNameFormat: "The full name should be in the format: [First Name] [Last Name].",
    avoidConsecutiveSpacesInName: "Please avoid using consecutive spaces in your name.",
    displayNameCannotBeUsername: "The display name cannot be the same as the username. Please choose a different display name.",
    avoidExcessiveConsecutiveCharsInFirstName: "Please avoid using excessive consecutive characters in your first name.",
    avoidExcessiveConsecutiveCharsInLastName: "Please avoid using excessive consecutive characters in your last name.",
    fullNameTooLongShortenName: "The full name is too long. Please use a shorter name.",
    enterDisplayNameToContinue: "Please enter a display name to continue.",
    fullNameCannotContainSpecialChars: "Full name cannot contain special characters. Please use alphabets only.",
    enterDisplayNameAgain: "Please enter your display name.",
    avoidExcessiveSpacesSpecialCharsInFullName: "Please avoid using excessive spaces and special characters in your full name.",
    capitalizeFirstLetterOfFirstName: "The first name should start with an uppercase letter.",
    capitalizeFirstLetterOfLastName: "The last name should start with an uppercase letter.",
    fullNameFormatCorrect: "The full name should be in the format: [First Name] [Last Name].",
    avoidExcessiveConsecutiveSpacesInDisplayName: "Please avoid using excessive consecutive spaces in your display name.",
    fullNameCannotContainNumbers: "Full name cannot contain numbers. Please use alphabets only.",
    displayNameTooLongShortenNameAgain: "The display name is too long. Please use a shorter name.",
    capitalizeFirstLetterOfEachNameInFullName: "Please capitalize the first letter of each name in your full name.",
    avoidConsecutiveUnderscoresInDisplayName: "Please avoid using consecutive underscores in your display name.",
  };
  
  const emailmsg = {
    enterEmailAddress: "Please enter your email address.",
    invalidEmailOrPassword: "Invalid email or Password. Please try again.",
    emailAlreadyRegistered: "The email address you entered is already registered. Please log in or use a different email.",
    emailDomainNotSupported: "Email domain is not supported. Please use a different email.",
    enterValidEmailAddress: "Please enter a valid email address.",
    emailDoesNotExist: "The email address you entered does not exist. Please check and try again.",
    emailTooLongShortenAddress: "The email address is too long. Please shorten it and try again.",
    emailMinLength: "The email address must be at least 5 characters long.",
    avoidExcessiveConsecutiveDotsInEmail: "Please avoid using excessive consecutive dots in your email address.",
    avoidConsecutiveUnderscoresInEmail: "Please avoid using consecutive underscores in your email address.",
    emailNotVerified: "Email address not verified. Please check your inbox for verification instructions.",
    emailCannotContainSpaces: "Email address cannot contain spaces. Please remove spaces and try again.",
    emailCannotStartWithDot: "Email address cannot start with a dot. Please enter a valid email address.",
    emailCannotEndWithDot: "Email address cannot end with a dot. Please enter a valid email address.",
    emailNotAllowed: "This email address is not allowed. Please use a different email.",
    emailAlreadyVerified: "The email address is already verified.",
    emailCannotContainLeadingOrTrailingSpaces: "Email address cannot contain leading or trailing spaces. Please enter a valid email address.",
    emailFromThisDomainNotAllowed: "Email address from this domain is not allowed. Please use a different email.",
    avoidExcessiveConsecutiveHyphensInEmail: "Please avoid using consecutive hyphens in your email address.",
    emailFromTemporaryDomainsNotAllowed: "Email address from temporary domains is not allowed. Please use a different email.",
    emailContainsInvalidChars: "Email address contains invalid characters. Please use a valid email address.",
    emailConfirmationTimeExceeded: "Email address confirmation time exceeded. Please request a new confirmation link.",
    emailCannotStartOrEndWithUnderscore: "Email address cannot start or end with an underscore. Please enter a valid email address.",
    emailShouldBeInLowercase: "Email address should be in lowercase. Please enter a valid email address.",
    emailTooLongShortenAddressAgain: "Email address is too long. Please use a shorter email address.",
    emailNotAssociatedWithAnyAccount: "The email address you entered is not associated with any account. Please sign up.",
    avoidExcessiveConsecutiveUnderscoresInEmailAgain: "Please avoid using consecutive underscores in your email address.",
    emailContainsRestrictedChars: "Email address contains restricted characters. Please use a valid email address.",
    confirmEmailToLogIn: "Please confirm your email address to log in. Check your inbox for the confirmation link.",
    avoidExcessiveConsecutivePeriodsInEmail: "Please avoid using consecutive periods in your email address.",
    enterValidEmailWithValidDomain: "Please enter a valid email address with a valid domain.",
    avoidConsecutiveAtSymbolsInEmail: "Please avoid using consecutive '@' symbols in your email address.",
    emailAssociatedWithDisabledAccount: "The email address you entered is associated with a disabled account. Please contact support for assistance.",
    emailShouldBeInLowercaseAgain: "Email address should be in lowercase. Please enter a valid email address.",
    emailNotAcceptedDueToDomainPolicies: "The email address you entered is not accepted due to domain policies. Please use a different email.",
    emailAssociatedWithBannedUser: "The email address you entered is associated with a banned user. Please contact support for assistance.",
    emailContainsRestrictedWords: "The email address you entered contains restricted words. Please use a different email.",
    emailFormatNotValid: "The email address format is not valid. Please enter a valid email address.",
    emailAssociatedWithInactiveAccount: "The email address you entered is associated with an inactive account. Please contact support for assistance.",
    emailAssociatedWithDeletedAccount: "The email address you entered is associated with a deleted account. Please contact support for assistance.",
    emailAssociatedWithSuspendedAccount: "The email address you entered is associated with a suspended account. Please contact support for assistance.",
    avoidExcessiveConsecutiveHyphensInEmailAgain: "Please avoid using excessive consecutive hyphens in your email address.",
    emailFormatNotSupported: "The email address format is not supported. Please enter a valid email address.",
    avoidConsecutiveUnderscoresAndPeriodsInEmail: "Please avoid using consecutive underscores and periods in your email address.",
  };
  
   const passwordMessages = {
    enterPassword: "Please enter your password.",
    passwordMinLength: "Password must be at least 8 characters long.",
    passwordTooLongShorten: "Password is too long. Please use a shorter password.",
    enterPasswordAgain: "Please enter your password.",
    incorrectPasswordOrEmail: "Incorrect Password or Email. Please try again.",
    passwordRequiresCombination: "Password must contain a combination of letters, numbers, and special characters.",
    passwordCannotContainSpaces: "Password cannot contain spaces. Please remove spaces and try again.",
    passwordCannotBeUsername: "Password cannot be the same as the username. Please choose a different password.",
    passwordTooCommon: "Password is too common. Please choose a more secure password.",
    passwordCannotContainUsername: "Password cannot contain the username. Please choose a different password.",
    passwordCannotContainPersonalInfo: "Password cannot contain personal information. Please choose a more secure password.",
    passwordsDoNotMatch: "Passwords do not match. Please enter the same password in both fields.",
    passwordTooWeak: "Password is too weak. Please choose a stronger password.",
    avoidConsecutiveNumbersInPassword: "Please avoid using consecutive numbers in your password.",
    avoidConsecutiveSpecialCharsInPassword: "Please avoid using consecutive special characters in your password.",
    passwordTooLongShortenAgain: "Password is too long. Please use a shorter password.",
    confirmPasswordToCompleteSignup: "Please confirm your password to complete the sign-up.",
    avoidRepeatedCharsInPassword: "Please avoid using repeated characters in your password.",
    passwordCannotContainName: "Password cannot contain your name. Please choose a different password.",
    passwordCannotContainDictionaryWords: "Password cannot contain common dictionary words. Please choose a more secure password.",
    passwordStrengthInsufficient: "Password strength is insufficient. Please choose a stronger password.",
    passwordFoundInLeakedDatabases: "Password has been found in leaked databases. Please choose a more secure password.",
    passwordRequirements1: " - Password must has contain 8-16 characters that include at least 1 (lowercase , uppercase , number, and special character)  Eg- (Deepu+@34)",
    passwordRequirements2: " - Password must has contain 8-16 characters that include at least 1 (lowercase , uppercase , number, and special ) character in (Deepu+@34)",
    passwordRequirements3: " - Password must has contain 8-16 characters that include at least 1 (lowercase , uppercase , number, and special ) character in (!@#$%^&_*)",
    avoidConsecutiveUppercaseInPassword: "Please avoid using consecutive uppercase letters in your password.",
    avoidConsecutiveLowercaseInPassword: "Please avoid using consecutive lowercase letters in your password.",
    enterPasswordToLogin: "Please enter your password to log in.",
    avoidConsecutiveSpecialCharsInPasswordAgain: "Please avoid using consecutive special characters in your password.",
    passwordCannotContainLeadingOrTrailingSpaces: "Password cannot contain leading or trailing spaces. Please enter a valid password.",
    avoidConsecutiveRepeatedCharsInPassword: "Please avoid using consecutive repeated characters in your password.",
    avoidSequentialNumbersInPassword: "Please avoid using sequential numbers in your password.",
    passwordRequiresCombinationOfChars: "Password must contain a combination of uppercase and lowercase letters, numbers, and special characters.",
    passwordCannotBeSameAsEmail: "Password cannot be the same as the email address. Please choose a different password.",
    passwordContainsCommonPattern: "Password contains a common pattern. Please choose a more secure password.",
    passwordsDoNotMatchAgain: "Passwords do not match. Please enter the same password in both fields.",
    passwordContainsBannedWords: "Password contains banned words. Please choose a more secure password.",
    confirmPasswordToCompleteSignupAgain: "Please confirm your password to complete the sign-up.",
    passwordsDoNotMatchOnceMore: "Passwords do not match. Please enter the same password in both fields.",
    acceptTermsToProceed: "Please accept the terms and conditions to proceed.",
    agreeToPrivacyPolicyToContinue: "Please agree to the privacy policy to continue.",
    subscribeToNewsletterForUpdates: "Please subscribe to the newsletter to receive updates"
  }
  

  const formErrorMessages = {
    nameEmptyError: "Name cannot be empty. Please enter your name.",
    nameLengthError: "Name is too long. Please use a shorter name.",
    dobError: "Invalid date of birth. Please enter a valid date.",
    ageError: "You must be at least 18 years old to create a profile.",
    addressEmptyError: "Address cannot be empty. Please enter your address.",
    addressLengthError: "Address is too long. Please use a shorter address.",
    emailInvalidError: "Invalid email address. Please enter a valid email.",
    emailEmptyError: "Email address cannot be empty. Please enter your email.",
    phoneInvalidError: "Invalid phone number. Please enter a valid phone number.",
    phoneEmptyError: "Phone number cannot be empty. Please enter your phone number.",
    bioLengthError: "Bio is too long. Please use a shorter bio.",
    usernameEmptyError: "Username cannot be empty. Please enter your username.",
    usernameLengthError: "Username is too long. Please use a shorter username.",
    usernameSpecialCharError: "Username cannot contain special characters. Please enter a valid username.",
    usernameTakenError: "Username is already taken. Please choose a different username."
  };
  
 
  
export { success_msg}